"use strict";
var peg = require("pegjs");
var fs = require("fs");
var lang = require("./peg-lang");
var GRAMMAR_FILE = process.argv[2];
var INPUT_FILE = process.argv[3];
console.log("Grammar file is: " + GRAMMAR_FILE);
var grammarString = fs.readFileSync(GRAMMAR_FILE, "utf8");
var parser = peg.generate(grammarString, { trace: true });
var input = fs.readFileSync(INPUT_FILE, "utf8").trim();
console.log("Input", input);
var r = parser.parse(input);
console.log(r);
var instructions = lang.generateInstructions(r);
var machine = new lang.Machine(instructions);
console.log('Built machine');
console.log(machine);
//machine.execute();
