"use strict";
var peg = require("pegjs");
var fs = require("fs");
var lang = require("./peg-lang");
var grammarString = fs.readFileSync("pegjs-grammar.txt", "utf8");
var parser = peg.generate(grammarString);
var r = parser.parse("while(1)do {  x  = 1+2}x=4");
var instructions = lang.generateInstructions(r);
var machine = new lang.Machine(instructions);
console.log('Built machine');
console.log(machine);
machine.execute();
